export const TableContainerLevel = {
  MATCHED_RECORDS: "Matched Records",
  FINAL_MERGED_DATAFRAME: "Final Merged Data Frame",
  NO_RECORDS_FOUND: "No Records Found",
};

export const tableHeader = {
  SERIAL_NUMBER: "S. No.",
  ERROR_NO: "ERROR NO",
  ANTHROPIC_AI_SUMMARY: "ANTHROPIC AI SUMMARY",
  CAUSED_BY_DETAILS: "CAUSED BY DETAILS",
  HISTORICAL_SOLUTION: "HISTORICAL SOLUTION",
  ERROR_HEADER: "ERROR HEADER",
  APP_NM: "APP NAME",
  MODULE_NM: "MODULE NAME",
  CLASS_NM: "CLASS NAME",
  METHOD_NM: "METHOD NAME",
  SEVERITY: "SEVERITY",
  CO_CD: "CO CD",
  ERR_TIMESTAMP: "ERROR TIMESTAMP",
  OCCURRENCE_COUNT: "OCCURRENCE COUNT",
  SERVER_NM: "SERVER NAME",
  PAGE_NAME: "PAGE NAME",
  BUG_TITLE: "BUG TITLE",
  CREATE_BUG: "CREATE BUG",
};
